# Generated by Django 4.2.13 on 2024-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
