# Generated by Django 4.2.13 on 2024-08-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_thumbnail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='access',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('nature', 'Nature'), ('cities', 'Cities'), ('sport', 'Sport'), ('relationship', 'Relationship')], default='nature', max_length=20),
        ),
    ]
