# Generated by Django 4.2.13 on 2024-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_access_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Cities', 'Cities'), ('Sport', 'Sport'), ('Relationship', 'Relationship')], default='nature', max_length=20),
        ),
    ]
